Repository apache/skywalking-nginx-lua, pull requests merged in 2020-03, with the labels that each got.

#11 Remove 3 `tonumber` to erase the i64 not supported in Lua issue.
  lib/skywalking/segment_ref_test.lua
  lib/skywalking/span_test.lua
  lib/skywalking/util.lua
Labels: bug

#12 fix ExitSpan#peer bug
  lib/skywalking/span.lua
Labels: bug

#13 Fix a wrong method name and expose the upstream address as the variable
  README.md
  examples/nginx.conf
  lib/skywalking/tracer.lua
  test/e2e/validator/docker/conf.d/nginx.conf
  test/e2e/validator/src/test/resources/expectedData.yaml
Labels: bug

#10 used the nginx lua code style.
  .gitignore
  README.md
  lib/skywalking/client.lua
  lib/skywalking/register.lua
  lib/skywalking/segment.lua
  lib/skywalking/segment_ref.lua
  lib/skywalking/segment_ref_test.lua
  lib/skywalking/span.lua
  lib/skywalking/span_test.lua
  lib/skywalking/tracer.lua
  lib/skywalking/tracing_context.lua
  lib/skywalking/tracing_context_test.lua
  t/segment_ref.t
  t/util.t
Labels: enhancement

#14 Set up release makefile and doc.
  Makefile
  README.md
Labels: documentation

#15 Create CHANGES.md
  CHANGES.md
Labels: documentation

#16 Add release doc for further release process.
  CHANGES.md
  README.md
  release.md
Labels: documentation

#17 Fix README.md
  README.md
Labels: documentation

#18 Fix typo
  README.md
Labels: documentation

#19 Remove a wrong statement in the release guide.
  release.md
Labels: documentation

#20 Copy paste issue.
  release.md
Labels: documentation

#21 Uniform the SpanLayer type name
  lib/skywalking/span_layer.lua
  test/e2e/validator/src/test/resources/expectedData.yaml
Labels: enhancement

#22 Downgrade log level to debug
  lib/skywalking/client.lua
Labels: enhancement

#23 Fix release.md markdown format.
  release.md
Labels: documentation

#25 Follow release doc changes.
  release.md
Labels: documentation

#26 Fix typo
  examples/nginx.conf
Labels: bug

#27 ERR define missed
  lib/skywalking/client.lua
Labels: bug
