Repository apache/skywalking-nginx-lua, pull requests merged in 2020-04, with the labels that each got.

#28 Fix README.md
  README.md
Labels: documentation

#33 fix wrong context carrier endpoint data
  lib/skywalking/span.lua
Labels: bug

#34 remove first ref variable
  lib/skywalking/tracing_context.lua
Labels: enhancement

#35 Implement correlation protocol
  .github/workflows/ci.yaml
  README.md
  examples/nginx.conf
  lib/skywalking/correlation_context.lua
  lib/skywalking/correlation_context_test.lua
  lib/skywalking/tracer.lua
  lib/skywalking/tracing_context.lua
  skywalking-nginx-lua-2.0-0.rockspec
Labels: enhancement

#32 rocks: fixed wrong version of luarocks.
  release.md
  rockspec/skywalking-nginx-lua-0.1-0.rockspec
  rockspec/skywalking-nginx-lua-0.2-0.rockspec
Labels: enhancement

#36 bugfix: used tag v0.1.0 for luarocks.
  rockspec/skywalking-nginx-lua-0.1-0.rockspec
Labels: documentation
