Repository apache/skywalking-nginx-lua, pull requests merged in 2020-02, with the labels that each got.

#1 license: add license info for lua-resty-http.
  LICENSE
  licenses/LICENSE-lua-resty-http.txt
Labels: documentation

#2 doc: emphasize that the finish should be called only when the output …
  README.md
  examples/nginx.conf
Labels: enhancement

#5 Revert "feature: add CI and test cases for ngx lua. (#3)"
  .github/workflows/ci.yaml
  lib/skywalking/segment.lua
  lib/skywalking/segment_ref.lua
  lib/skywalking/tracing_context.lua
  lib/skywalking/util.lua
  lib/skywalking/util_test.lua
  t/util.t
Labels: bug

#6 Submit doc about how to debug startup env.
  README.md
Labels: documentation

#7 feature: add ngx lua github action and test cases.
  .github/workflows/ci.yaml
  lib/skywalking/segment.lua
  lib/skywalking/segment_ref.lua
  lib/skywalking/tracing_context.lua
  lib/skywalking/util.lua
  lib/skywalking/util_test.lua
  t/util.t
Labels: enhancement

#8 fix register local.
  .gitignore
  lib/skywalking/client.lua
  lib/skywalking/tracer.lua
Labels: bug

#9 add luarocks for skywalking-nginx-lua.
  skywalking-nginx-lua-1.0-0.rockspec
Labels: enhancement
