Repository apache/skywalking-nginx-lua, pull requests merged in 2021-12, with the labels that each got.

#89 draft a new version 0.6.0
  rockspec/skywalking-nginx-lua-0.6.0-0.rockspec
Labels: documentation

#90 correct the branch name in rockspec
  rockspec/skywalking-nginx-lua-0.6.0-0.rockspec
Labels: bug

#91 Update log4j to 2.17.1 to address CVE-2021-44832.
  test/e2e/e2e-test/pom.xml
Labels: test
